/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formlar;

import DBConnection.allConnections;
import Modeller.tblegitimprogrami;
import java.beans.Statement;
import java.lang.reflect.Executable;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author vektorel
 */
public class frmegitimprogrami extends javax.swing.JFrame {
    allConnections baglanti = new allConnections();
    ArrayList<Object> egitimgrubu = new ArrayList<>();
    Modeller.tblegitimprogrami tmpegitimprogrami;
    /**
     * Creates new form frmegitimprogrami
     */
    public frmegitimprogrami() {
        initComponents();
        
        DBCRUD.PostgreSQL.tblegitimprogrami db = new DBCRUD.PostgreSQL.tblegitimprogrami();
        List<Object> liste = db.Listele();
        updateTable(liste, jTable1);
        
        btnyenikaydet.setEnabled(true);
        btnkaydet.setEnabled(false);
        btnduzenle.setEnabled(true);
        btnsorgula.setEnabled(true);
        btnsil.setEnabled(true);
        
        txtid.setEditable(false);
        txttarih.setEditable(false);
        txtgun.setEditable(false);
        txtaletid.setEditable(false);
        txtset.setEditable(false);
        txttekrar.setEditable(false);
        txtsiralama.setEditable(false);
        txtegitimgrubu.setEditable(false);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMPopKaydet = new javax.swing.JMenuItem();
        jMPopDuzenle = new javax.swing.JMenuItem();
        jMPopSil = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txttarih = new javax.swing.JFormattedTextField();
        txtgun = new javax.swing.JTextField();
        txtaletid = new javax.swing.JTextField();
        txtset = new javax.swing.JTextField();
        txttekrar = new javax.swing.JTextField();
        txtsiralama = new javax.swing.JTextField();
        txtegitimgrubu = new javax.swing.JTextField();
        btnyenikaydet = new javax.swing.JButton();
        btnkaydet = new javax.swing.JButton();
        btnduzenle = new javax.swing.JButton();
        btnsorgula = new javax.swing.JButton();
        btnsil = new javax.swing.JButton();
        btncikis = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMPopKaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kaydet_popup_16px.png"))); // NOI18N
        jMPopKaydet.setText("Kaydet");
        jMPopKaydet.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMPopKaydetAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPopupMenu1.add(jMPopKaydet);

        jMPopDuzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/duzenle_popup_16.png"))); // NOI18N
        jMPopDuzenle.setText("Düzenle");
        jMPopDuzenle.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMPopDuzenleAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPopupMenu1.add(jMPopDuzenle);

        jMPopSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trash_23px.png"))); // NOI18N
        jMPopSil.setText("Sil");
        jMPopSil.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMPopSilAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPopupMenu1.add(jMPopSil);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EGITIM PROGRAMI");

        jLabel1.setText("Id");

        jLabel2.setText("Tarih");

        jLabel3.setText("Gun");

        jLabel4.setText("Alet Id");

        jLabel5.setText("Set");

        jLabel6.setText("Tekrar");

        jLabel7.setText("Sıralama");

        jLabel8.setText("Egitim Grubu");

        try {
            txttarih.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnyenikaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yeni_kayit.png"))); // NOI18N
        btnyenikaydet.setText("Yeni Kaydet");
        btnyenikaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenikaydetActionPerformed(evt);
            }
        });

        btnkaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kaydet.png"))); // NOI18N
        btnkaydet.setText("Kaydet");
        btnkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaydetActionPerformed(evt);
            }
        });

        btnduzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/duzenle.png"))); // NOI18N
        btnduzenle.setText("Duzenle");
        btnduzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnduzenleActionPerformed(evt);
            }
        });

        btnsorgula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sorgula_koyumavi_26px.png"))); // NOI18N
        btnsorgula.setText("Sorgula");
        btnsorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsorgulaActionPerformed(evt);
            }
        });

        btnsil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sil.png"))); // NOI18N
        btnsil.setText("Sil");
        btnsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsilActionPerformed(evt);
            }
        });

        btncikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cikis_26.png"))); // NOI18N
        btncikis.setText("Çıkış");
        btncikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncikisActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tarih", "Gün", "Alet_id", "Set", "Tekrar", "Sıralama", "Egetim Grubu"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnyenikaydet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnduzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btncikis, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsiralama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttekrar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtset, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaletid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtgun, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttarih, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtegitimgrubu)
                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txttarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtgun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtaletid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsiralama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtegitimgrubu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnyenikaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnkaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnduzenle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsorgula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnyenikaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenikaydetActionPerformed
            DBCRUD.PostgreSQL.tblegitimprogrami db = new DBCRUD.PostgreSQL.tblegitimprogrami();
            
            btnyenikaydet.setEnabled(false);
            btnkaydet.setEnabled(true);
            btnduzenle.setEnabled(false);
            btnsorgula.setEnabled(false);
            btnsil.setEnabled(false);
            
            txtid.setEditable(true);
            txttarih.setEditable(true);
            txtgun.setEditable(true);
            txtaletid.setEditable(true);
            txtset.setEditable(true);
            txttekrar.setEditable(true);
            txtsiralama.setEditable(true);
            txtegitimgrubu.setEditable(true);
            
            txtid.setText("");
            txttarih.setText("");
            txtgun.setText("");
            txtaletid.setText("");
            txtset.setText("");
            txttekrar.setText("");
            txtsiralama.setText("");
            txtegitimgrubu.setText("");
    }//GEN-LAST:event_btnyenikaydetActionPerformed

    private void btnkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaydetActionPerformed
        //String sorgu = ("insert into tblegitimprogrami set (tarih , gun , alet_id , set , tekrar , siralama , egitimgrubu_id) values ('"+txttarih.getText()+"','"+txtgun.getText()+"','"+txtaletid.getText()+"','"+txtset.getText()+"','"+txttekrar.getText()+"','"+txtsiralama.getText()+"','"+txtegitimgrubu.getText()+"')");
        
        DBCRUD.PostgreSQL.tblegitimprogrami db = new DBCRUD.PostgreSQL.tblegitimprogrami();
        
        //tmpegitimprogrami = new Modeller.tblegitimprogrami();
        //DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        Modeller.tblegitimprogrami model = new Modeller.tblegitimprogrami();
        
        //Butonların Görünürlüğünü Sağlıyoruz.
        btnyenikaydet.setEnabled(true);
        btnkaydet.setEnabled(false);
        btnduzenle.setEnabled(true);
        btnsorgula.setEnabled(true);
        btnsil.setEnabled(true);
        
        //Modeller içerisinde yer alan eğitimgrubu sınıfını set ve get metodlarını çağırıyoruz.
        model.setId(Long.valueOf(this.txtid.getText()));
        model.setTarih(Date.from(LocalDate.parse(this.txttarih.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd")).atStartOfDay().toInstant(ZoneOffset.UTC)));
        model.setGun(this.txtgun.getText());
        model.setAletid(Long.valueOf(this.txtaletid.getText()));
        model.setSet(Integer.valueOf(this.txtset.getText()));
        model.setTekrar(Integer.valueOf(this.txttekrar.getText()));
        model.setSiralama(Integer.valueOf(this.txtsiralama.getText()));
        model.setEgitimgrupid(Long.valueOf(this.txtegitimgrubu.getText()));
        
        //CRUD içerisinde ki kaydet metodunu çağırıyoruz.
        db.Kaydet(model);
        
        //Text Field Boşaltıyoruz.
        txtid.setText("");
        txttarih.setText("");
        txtgun.setText("");
        txtaletid.setText("");
        txtset.setText("");
        txttekrar.setText("");
        txtsiralama.setText("");
        txtegitimgrubu.setText("");
        
        
        //Yenile Ardından Tekrardan Listeyi Çağırma
        List<Object> liste = db.Listele();
        updateTable(liste, jTable1);
        
        
        //JTable Yenileme
        DefaultTableModel yenile = (DefaultTableModel)jTable1.getModel();
        yenile.setRowCount(1000);
        
        
        //Popup Mesaj
        //JOptionPane.showMessageDialog(null, "KAYIT İŞLEMİ BAŞARI İLE GERÇEKLEŞTİRİLMİŞTİR.", "KAYIT İŞLEMİ",
                //JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnkaydetActionPerformed

    private void btnduzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnduzenleActionPerformed
        DBCRUD.PostgreSQL.tblegitimprogrami db = new DBCRUD.PostgreSQL.tblegitimprogrami();
        Modeller.tblegitimprogrami model = new Modeller.tblegitimprogrami();
        
        txtid.setEditable(true);
        txttarih.setEditable(true);
        txtgun.setEditable(true);
        txtaletid.setEditable(true);
        txtset.setEditable(true);
        txttekrar.setEditable(true);
        txtsiralama.setEditable(true);
        txtegitimgrubu.setEditable(true);
        
        btnyenikaydet.setEnabled(false);
        btnkaydet.setEnabled(true);
        btnduzenle.setEnabled(true);
        btnsorgula.setEnabled(false);
        btnsil.setEnabled(false);
        
        
        
        model.setId(Long.valueOf(this.txtid.getText()));
        model.setTarih(Date.from(LocalDate.parse(this.txttarih.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd")).atStartOfDay().toInstant(ZoneOffset.UTC)));
        model.setGun(this.txtgun.getText());
        model.setAletid(Long.valueOf(this.txtaletid.getText()));
        model.setSet(Integer.valueOf(this.txtset.getText()));
        model.setTekrar(Integer.valueOf(this.txttekrar.getText()));
        model.setSiralama(Integer.valueOf(this.txtsiralama.getText()));
        model.setEgitimgrupid(Long.valueOf(this.txtegitimgrubu.getText()));
        
        db.Duzenle(model);
        
        
        //List<Object> liste = db.Listele();
        //setTable(liste, jTable1);
        
        
        
        //JOptionPane.showMessageDialog(null, "DÜZENLEME İŞLEMİ BAŞARI İLE GERÇEKLEŞTİRİLMİŞTİR.", "DÜZENLEME İŞLEMİ",
        //JOptionPane.INFORMATION_MESSAGE);
        
        DefaultTableModel yenile = (DefaultTableModel)jTable1.getModel();
        yenile.setRowCount(1000);
        
    }//GEN-LAST:event_btnduzenleActionPerformed

    private void btnsorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsorgulaActionPerformed
        DBCRUD.PostgreSQL.tblegitimprogrami db = new DBCRUD.PostgreSQL.tblegitimprogrami();
        db.Bul(0);
        JOptionPane.showMessageDialog(null, "SORGULAMA İŞLEMİ BAŞARI İLE GERÇEKLEŞTİRİLMİŞTİR.", "BULMA İŞLEMİ",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnsorgulaActionPerformed

    private void btnsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsilActionPerformed
        DBCRUD.PostgreSQL.tblegitimprogrami db = new DBCRUD.PostgreSQL.tblegitimprogrami();
        Modeller.tblegitimprogrami model = new Modeller.tblegitimprogrami();
       
        model.setId(Long.valueOf(this.txtid.getText()));
        db.Sil(0);
        
        JOptionPane.showMessageDialog(null, "SİLME İŞLEMİ BAŞARI İLE GERÇEKLEŞTİRİLMİŞTİR.", "SİLME İŞLEMİ",
                JOptionPane.INFORMATION_MESSAGE);
        
        DefaultTableModel yenile = (DefaultTableModel)jTable1.getModel();
        yenile.rowsRemoved(txtid.remove());
    }//GEN-LAST:event_btnsilActionPerformed

    private void btncikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncikisActionPerformed
        dispose();
    }//GEN-LAST:event_btncikisActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        txtid.setText(model.getValueAt(i,0).toString());
        txttarih.setText(model.getValueAt(i,1).toString());
        txtgun.setText(model.getValueAt(i,2).toString());
        txtaletid.setText(model.getValueAt(i,3).toString());
        txtset.setText(model.getValueAt(i,4).toString());
        txtsiralama.setText(model.getValueAt(i,5).toString());
        txttekrar.setText(model.getValueAt(i,6).toString());
        txtegitimgrubu.setText(model.getValueAt(i,7).toString());
        
        /*txtid.setEditable(true);
        txttarih.setEditable(true);
        txtgun.setEditable(true);
        txtaletid.setEditable(true);
        txtset.setEditable(true);
        txttekrar.setEditable(true);
        txtsiralama.setEditable(true);
        txtegitimgrubu.setEditable(true);*/
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        if(evt.isPopupTrigger())
        {
            jPopupMenu1.show(this,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void jMPopKaydetAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMPopKaydetAncestorAdded
         DBCRUD.PostgreSQL.tblegitimprogrami db = new DBCRUD.PostgreSQL.tblegitimprogrami();
        Modeller.tblegitimprogrami model = new Modeller.tblegitimprogrami();
        
        txtid.setEditable(true);
        txttarih.setEditable(true);
        txtgun.setEditable(true);
        txtaletid.setEditable(true);
        txtset.setEditable(true);
        txttekrar.setEditable(true);
        txtsiralama.setEditable(true);
        txtegitimgrubu.setEditable(true);
        
        model.setId(Long.valueOf(this.txtid.getText()));
        model.setTarih(Date.from(LocalDate.parse(this.txttarih.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd")).atStartOfDay().toInstant(ZoneOffset.UTC)));
        model.setGun(this.txtgun.getText());
        model.setAletid(Long.valueOf(this.txtaletid.getText()));
        model.setSet(Integer.valueOf(this.txtset.getText()));
        model.setTekrar(Integer.valueOf(this.txttekrar.getText()));
        model.setSiralama(Integer.valueOf(this.txtsiralama.getText()));
        model.setEgitimgrupid(Long.valueOf(this.txtegitimgrubu.getText()));
        
        //CRUD içerisinde ki kaydet metodunu çağırıyoruz.
        db.Kaydet(model);
        
        //Text Field Boşaltıyoruz.
        /*txtid.setText("");
        txttarih.setText("");
        txtgun.setText("");
        txtaletid.setText("");
        txtset.setText("");
        txttekrar.setText("");
        txtsiralama.setText("");
        txtegitimgrubu.setText("");*/
        
        DefaultTableModel yenile = (DefaultTableModel)jTable1.getModel();
        yenile.setRowCount(0);
        
        //Yenile Ardından Tekrardan Listeyi Çağırma
        List<Object> liste = db.Listele();
        updateTable(liste, jTable1);
        
        //JTable Yenileme
        
    }//GEN-LAST:event_jMPopKaydetAncestorAdded

    private void jMPopDuzenleAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMPopDuzenleAncestorAdded
        DBCRUD.PostgreSQL.tblegitimprogrami db = new DBCRUD.PostgreSQL.tblegitimprogrami();
        Modeller.tblegitimprogrami model = new Modeller.tblegitimprogrami();
        
        txtid.setEditable(true);
        txttarih.setEditable(true);
        txtgun.setEditable(true);
        txtaletid.setEditable(true);
        txtset.setEditable(true);
        txttekrar.setEditable(true);
        txtsiralama.setEditable(true);
        txtegitimgrubu.setEditable(true);
        
        btnyenikaydet.setEnabled(false);
        btnkaydet.setEnabled(true);
        btnduzenle.setEnabled(false);
        btnsorgula.setEnabled(false);
        btnsil.setEnabled(false);
        
        
        model.setId(Long.valueOf(this.txtid.getText()));
        model.setTarih(Date.from(LocalDate.parse(this.txttarih.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd")).atStartOfDay().toInstant(ZoneOffset.UTC)));
        model.setGun(this.txtgun.getText());
        model.setAletid(Long.valueOf(this.txtaletid.getText()));
        model.setSet(Integer.valueOf(this.txtset.getText()));
        model.setTekrar(Integer.valueOf(this.txttekrar.getText()));
        model.setSiralama(Integer.valueOf(this.txtsiralama.getText()));
        model.setEgitimgrupid(Long.valueOf(this.txtegitimgrubu.getText()));
        
        db.Duzenle(model);
        
        DefaultTableModel yenile = (DefaultTableModel)jTable1.getModel();
        yenile.setRowCount(0);
        //List<Object> liste = db.Listele();
        //setTable(liste, jTable1);
        
        //JOptionPane.showMessageDialog(null, "DÜZENLEME İŞLEMİ BAŞARI İLE GERÇEKLEŞTİRİLMİŞTİR.", "DÜZENLEME İŞLEMİ",
        //JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_jMPopDuzenleAncestorAdded

    private void jMPopSilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMPopSilAncestorAdded
     
    }//GEN-LAST:event_jMPopSilAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmegitimprogrami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmegitimprogrami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmegitimprogrami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmegitimprogrami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmegitimprogrami().setVisible(true);
            }
        });
    }

    private void updateTable(List<Object> liste, JTable table) {
       
            
            Object[][] data = new Object[liste.size()][8];
            
            for(int i = 0; i < liste.size(); i++) {
                data[i][0] = ((Modeller.tblegitimprogrami) liste.get(i)).getId();
                data[i][1] = ((Modeller.tblegitimprogrami) liste.get(i)).getTarih();
                data[i][2] = ((Modeller.tblegitimprogrami) liste.get(i)).getGun();
                data[i][3] = ((Modeller.tblegitimprogrami) liste.get(i)).getAletid();
                data[i][4] = ((Modeller.tblegitimprogrami) liste.get(i)).getSet();
                data[i][5] = ((Modeller.tblegitimprogrami) liste.get(i)).getTekrar();
                data[i][6] = ((Modeller.tblegitimprogrami) liste.get(i)).getSiralama();
                data[i][7] = ((Modeller.tblegitimprogrami) liste.get(i)).getEgitimgrupid();
            }
            
            TableModel model = new DefaultTableModel(data, new Object[]{"Id", "Tarih", "Gün", "Alet_Id", "Set", "Tekrar", "Sıralama", "Egitim Grubu"});
            
            table.setModel(model);
    }
    
    /*private void setTable(List<Object> liste, JTable table) {
       
            
            Object[][] data = new Object[liste.size()][8];
            
            for(int i = 0; i < liste.size(); i++) {
                data[i][0] = ((Modeller.tblegitimprogrami) liste.get(i)).getId();
                data[i][1] = ((Modeller.tblegitimprogrami) liste.get(i)).getTarih();
                data[i][2] = ((Modeller.tblegitimprogrami) liste.get(i)).getGun();
                data[i][3] = ((Modeller.tblegitimprogrami) liste.get(i)).getAletid();
                data[i][4] = ((Modeller.tblegitimprogrami) liste.get(i)).getSet();
                data[i][5] = ((Modeller.tblegitimprogrami) liste.get(i)).getTekrar();
                data[i][6] = ((Modeller.tblegitimprogrami) liste.get(i)).getSiralama();
                data[i][7] = ((Modeller.tblegitimprogrami) liste.get(i)).getEgitimgrupid();
            }
            
            TableModel model = new DefaultTableModel(data, new Object[]{"Id", "Tarih", "Gün", "Alet_Id", "Set", "Tekrar", "Sıralama", "Egitim Grubu"});
            
            table.setModel(model);
    }*/
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncikis;
    private javax.swing.JButton btnduzenle;
    private javax.swing.JButton btnkaydet;
    private javax.swing.JButton btnsil;
    private javax.swing.JButton btnsorgula;
    private javax.swing.JButton btnyenikaydet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMPopDuzenle;
    private javax.swing.JMenuItem jMPopKaydet;
    private javax.swing.JMenuItem jMPopSil;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtaletid;
    private javax.swing.JTextField txtegitimgrubu;
    private javax.swing.JTextField txtgun;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtset;
    private javax.swing.JTextField txtsiralama;
    private javax.swing.JFormattedTextField txttarih;
    private javax.swing.JTextField txttekrar;
    // End of variables declaration//GEN-END:variables

    private void jTable1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
